# Generated by Django 3.0.1 on 2020-07-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
